apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
        - name: todo-list
          image: ghcr.io/adisoncavani/todo-list:latest
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_GITHUB_ID
              valueFrom:
                secretKeyRef:
                  name: auth-github-id
                  key: AUTH_GITHUB_ID
            - name: AUTH_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-github-secret
                  key: AUTH_GITHUB_SECRET
            - name: AUTH_GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: auth-google-id
                  key: AUTH_GOOGLE_ID
            - name: AUTH_GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-google-secret
                  key: AUTH_GOOGLE_SECRET
            - name: DATABASE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: database-connection-string
                  key: DATABASE_CONNECTION_STRING
            - name: NEXT_PUBLIC_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: next-public-sentry-dsn
                  key: NEXT_PUBLIC_SENTRY_DSN
            - name: PRODUCTION_URL
              valueFrom:
                secretKeyRef:
                  name: production-url
                  key: PRODUCTION_URL
