version: '3.7'

services:
  dynamodb:
    image:  amazon/dynamodb-local
    hostname: dynamo
    restart: always
    command: '-jar DynamoDBLocal.jar -sharedDb'
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    ports:
      - ${PORT:-8000}:8000

  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --cli-input-json file:///dynamodb.json --endpoint-url http://dynamo:8000"
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./dynamodb.json:/dynamodb.json
    links:
      - dynamodb